name: PostSubmit

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # code and tests
      - '**/*.rs'
      # dependencies
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '.github/workflows/postsubmit.yml'

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: full
  RUST_LIB_BACKTRACE: full

jobs:
  coverage:
    name: coverage
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
        with:
          persist-credentials: false

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov cargo command
        run: cargo install cargo-llvm-cov

      - name: Generate coverage report
        run: cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2.1.0